# Generated by Django 4.0.3 on 2022-04-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fanPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('defScore', models.IntegerField(default=0)),
                ('offScore', models.IntegerField(default=0)),
                ('efficiency', models.IntegerField(default=0)),
                ('salary', models.IntegerField(default=1000)),
            ],
        ),
    ]
