# Generated by Django 4.0.3 on 2022-04-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanplayer',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
