# Generated by Django 4.0.3 on 2022-04-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0002_fanplayer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanplayer',
            name='age',
            field=models.FloatField(default=18),
        ),
    ]
