# Generated by Django 4.0.3 on 2022-04-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0003_alter_fanplayer_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fanplayer',
            name='defScore',
        ),
        migrations.RemoveField(
            model_name='fanplayer',
            name='offScore',
        ),
        migrations.AddField(
            model_name='fanplayer',
            name='overall',
            field=models.FloatField(default=0, verbose_name='Overall'),
        ),
        migrations.AddField(
            model_name='fanplayer',
            name='passing_grade',
            field=models.FloatField(default=0, verbose_name='Passing_grade'),
        ),
        migrations.AddField(
            model_name='fanplayer',
            name='position',
            field=models.CharField(default='', max_length=255, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='fanplayer',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='fanplayer',
            name='rebounding_grade',
            field=models.FloatField(default=0, verbose_name='Rebounding_grade'),
        ),
        migrations.AddField(
            model_name='fanplayer',
            name='scoring_grade',
            field=models.FloatField(default=0, verbose_name='Scoring_grade'),
        ),
        migrations.AddField(
            model_name='fanplayer',
            name='turnover_grade',
            field=models.FloatField(default=0, verbose_name='Turnover_grade'),
        ),
        migrations.AlterField(
            model_name='fanplayer',
            name='age',
            field=models.FloatField(default=18, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='fanplayer',
            name='efficiency',
            field=models.FloatField(default=0, verbose_name='Efficiency'),
        ),
        migrations.AlterField(
            model_name='fanplayer',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
        ),
    ]
