# Generated by Django 4.0.3 on 2022-04-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0004_remove_fanplayer_defscore_remove_fanplayer_offscore_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('position', models.CharField(default='', max_length=255, verbose_name='Position')),
                ('age', models.FloatField(default=18, verbose_name='Age')),
                ('scoring_grade', models.FloatField(default=0, verbose_name='Scoring_grade')),
                ('passing_grade', models.FloatField(default=0, verbose_name='Passing_grade')),
                ('rebounding_grade', models.FloatField(default=0, verbose_name='Rebounding_grade')),
                ('rating', models.FloatField(default=0, verbose_name='Rating')),
                ('efficiency', models.FloatField(default=0, verbose_name='Efficiency')),
                ('turnover_grade', models.FloatField(default=0, verbose_name='Turnover_grade')),
                ('overall', models.FloatField(default=0, verbose_name='Overall')),
                ('salary', models.IntegerField(default=0)),
            ],
        ),
    ]
