# Generated by Django 4.0.3 on 2022-04-30 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0005_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='position',
        ),
    ]
