# Generated by Django 4.0.3 on 2022-04-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0006_remove_team_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_created_teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_age', models.FloatField(default=18)),
                ('mean_scoring', models.FloatField(default=0)),
                ('mean_passing', models.FloatField(default=0)),
                ('mean_rebounding', models.FloatField(default=0)),
                ('mean_rating', models.FloatField(default=0)),
                ('mean_efficiency', models.FloatField(default=0)),
                ('mean_turnOver_grade', models.FloatField(default=0)),
                ('mean_overall', models.FloatField(default=0)),
                ('total_spendings', models.FloatField(default=0)),
            ],
        ),
    ]
