# Generated by Django 4.0.3 on 2022-05-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0007_user_created_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_created_teams',
            name='team_name',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
        ),
    ]
