# Generated by Django 4.0.3 on 2022-04-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='FULL NAME')),
                ('team', models.CharField(max_length=4, verbose_name='TEAM')),
                ('position', models.CharField(max_length=4, verbose_name='POS')),
                ('age', models.IntegerField(verbose_name='AGE')),
                ('gamesPlayed', models.IntegerField(verbose_name='GP')),
                ('minPerGame', models.FloatField(verbose_name='MPG')),
                ('ftPercent', models.FloatField(verbose_name='FT%')),
                ('twoPointAttempts', models.IntegerField(verbose_name='2PA')),
                ('twoPointPercent', models.FloatField(verbose_name='2P%')),
                ('threePointAttempts', models.IntegerField(verbose_name='3PA')),
                ('threePointPercent', models.FloatField(verbose_name='3P%')),
                ('fieldGoalPercent', models.FloatField(verbose_name='eFG%')),
                ('pointsPerGame', models.FloatField(verbose_name='PPG')),
                ('reboundsPerGame', models.FloatField(verbose_name='RPG')),
                ('assistsPerGame', models.FloatField(verbose_name='APG')),
                ('stealsPerGame', models.FloatField(verbose_name='SPG')),
                ('blocksPerGame', models.FloatField(verbose_name='BPG')),
                ('TOPerGame', models.FloatField(verbose_name='TOPG')),
                ('offRtg', models.FloatField(verbose_name='ORTG')),
                ('defRtg', models.FloatField(verbose_name='DRTG')),
            ],
        ),
    ]
