# Generated by Django 4.0.3 on 2022-04-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='freethrowAtt',
            field=models.IntegerField(default=0, verbose_name='FTA'),
        ),
        migrations.AddField(
            model_name='player',
            name='toPercent',
            field=models.FloatField(default=0, verbose_name='TO%'),
        ),
        migrations.AddField(
            model_name='player',
            name='trbPercent',
            field=models.FloatField(default=0, verbose_name='TRB%'),
        ),
        migrations.AddField(
            model_name='player',
            name='tsPercent',
            field=models.FloatField(default=0, verbose_name='TS%'),
        ),
        migrations.AddField(
            model_name='player',
            name='usgRate',
            field=models.FloatField(default=0, verbose_name='USG%'),
        ),
        migrations.AddField(
            model_name='player',
            name='viv',
            field=models.FloatField(default=0, verbose_name='VIV'),
        ),
        migrations.AlterField(
            model_name='player',
            name='TOPerGame',
            field=models.FloatField(default=0, verbose_name='TOPG'),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=0, verbose_name='AGE'),
        ),
        migrations.AlterField(
            model_name='player',
            name='assistsPerGame',
            field=models.FloatField(default=0, verbose_name='APG'),
        ),
        migrations.AlterField(
            model_name='player',
            name='blocksPerGame',
            field=models.FloatField(default=0, verbose_name='BPG'),
        ),
        migrations.AlterField(
            model_name='player',
            name='defRtg',
            field=models.FloatField(default=0, verbose_name='DRTG'),
        ),
        migrations.AlterField(
            model_name='player',
            name='fieldGoalPercent',
            field=models.FloatField(default=0, verbose_name='eFG%'),
        ),
        migrations.AlterField(
            model_name='player',
            name='ftPercent',
            field=models.FloatField(default=0, verbose_name='FT%'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gamesPlayed',
            field=models.IntegerField(default=0, verbose_name='GP'),
        ),
        migrations.AlterField(
            model_name='player',
            name='minPerGame',
            field=models.FloatField(default=0, verbose_name='MPG'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='FULL NAME'),
        ),
        migrations.AlterField(
            model_name='player',
            name='offRtg',
            field=models.FloatField(default=0, verbose_name='ORTG'),
        ),
        migrations.AlterField(
            model_name='player',
            name='pointsPerGame',
            field=models.FloatField(default=0, verbose_name='PPG'),
        ),
        migrations.AlterField(
            model_name='player',
            name='reboundsPerGame',
            field=models.FloatField(default=0, verbose_name='RPG'),
        ),
        migrations.AlterField(
            model_name='player',
            name='stealsPerGame',
            field=models.FloatField(default=0, verbose_name='SPG'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(default='', max_length=4, verbose_name='TEAM'),
        ),
        migrations.AlterField(
            model_name='player',
            name='threePointAttempts',
            field=models.IntegerField(default=0, verbose_name='3PA'),
        ),
        migrations.AlterField(
            model_name='player',
            name='threePointPercent',
            field=models.FloatField(default=0, verbose_name='3P%'),
        ),
        migrations.AlterField(
            model_name='player',
            name='twoPointAttempts',
            field=models.IntegerField(default=0, verbose_name='2PA'),
        ),
        migrations.AlterField(
            model_name='player',
            name='twoPointPercent',
            field=models.FloatField(default=0, verbose_name='2P%'),
        ),
    ]
