# Generated by Django 4.0.3 on 2022-04-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_player_freethrowatt_player_topercent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='assistPercent',
            field=models.FloatField(default=0, verbose_name='AST%'),
        ),
        migrations.AddField(
            model_name='player',
            name='minPercent',
            field=models.FloatField(default=0, verbose_name='MIN%'),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.FloatField(default=0, verbose_name='AGE'),
        ),
    ]
