# Generated by Django 4.0.3 on 2022-04-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_player_assistpercent_player_minpercent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(default='', max_length=4, verbose_name='POS'),
        ),
    ]
