# Generated by Django 4.0.3 on 2022-04-14 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_player_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='stealsPerGame',
            new_name='stealPerGame',
        ),
    ]
